// SCH-EVENTS-ACTIONS — imagem 3: Architecture Center 2a28bd (Nov 2025),
// "SAP CAP Framework for Events to Business Actions Integration", Diagram
// Level 2. Facto verificado no site: a própria SAP diz que o framework CAP
// "não é produto standard SAP" — é uma aplicação de referência (open-source,
// SAP-samples) com 3 módulos: Modeler, Processor, Monitoring.
export default {
  id: 'events-actions',
  titulo: { pt: 'Events → Business Actions (CAP)', en: 'Events → Business Actions (CAP)', fr: 'Événements → Actions métier (CAP)', de: 'Events → Business Actions (CAP)', es: 'Eventos → Acciones de negocio (CAP)' },
  hero: { pt: 'Eventos de fábrica/IoT entram pela Advanced Event Mesh; um framework CAP (Node.js) traduz cada evento numa acção de negócio no S/4 via Build Process Automation Decisions.', en: 'Plant/IoT events enter through Advanced Event Mesh; a CAP (Node.js) framework turns each event into a business action in S/4 via Build Process Automation Decisions.' },
  fonte: 'SAP Architecture Center 2a28bd — Events to Business Actions · Diagram Level 2 · framework de referência, não produto standard',
  dominio: 'integration',
  cenarios: [{ id: 'completo', nome: { pt: 'Fluxo completo', en: 'Full flow' } }],
  computarEstiloNo: () => ({}),
  nodes: [
    { id: 'sources', type: 'container', position: { x: 10, y: 150 }, style: { width: 210, height: 130, zIndex: 0 }, data: { titulo: 'Event Sources', icone: 'factory', dominio: 'nonsap', subtitulo: 'Industry 4.0 · Systems · Warehouses · Logistics · Plants' } },
    { id: 'producers', type: 'container', position: { x: 250, y: 100 }, style: { width: 190, height: 260, zIndex: 0 }, data: { titulo: 'Event Producer Systems', dominio: 'nonsap' } },
    { id: 'iot', type: 'item', position: { x: 265, y: 140 }, style: { width: 160, height: 60, zIndex: 1 }, data: { label: 'IoT Platforms', nota: 'Hyperscaler IoT (Azure / AWS) · other', cardId: 'iot', dominio: 'nonsap' } },
    { id: 'third', type: 'item', position: { x: 265, y: 215 }, style: { width: 160, height: 60, zIndex: 1 }, data: { label: '3rd Party Platforms', nota: 'apps · enterprise apps · productivity tools', dominio: 'nonsap' } },
    { id: 'actor-admin', type: 'actor', position: { x: 10, y: 400 }, data: { label: 'Application Administrator', icone: 'user' } },
    { id: 'actor-clients', type: 'actor', position: { x: 130, y: 400 }, data: { label: 'Application Clients', icone: 'smartphone' } },
    { id: 'btp', type: 'container', position: { x: 470, y: 20 }, style: { width: 640, height: 600, zIndex: 0 }, data: { titulo: 'SAP BTP', icone: 'cloud', dominio: 'btp', cardId: 'btp' } },
    { id: 'subaccount', type: 'container', position: { x: 490, y: 60 }, style: { width: 600, height: 380, zIndex: 1 }, data: { titulo: 'Subaccount · Multi-Cloud', dominio: 'btp' } },
    { id: 'aem', type: 'item', position: { x: 505, y: 150 }, style: { width: 140, height: 60, zIndex: 2 }, data: { label: 'Integration Suite, advanced event mesh', cardId: 'advanced-event-mesh', dominio: 'btp' } },
    { id: 'workzone', type: 'item', position: { x: 505, y: 260 }, style: { width: 140, height: 50, zIndex: 2 }, data: { label: 'Build Work Zone, advanced edition', cardId: 'workzone', dominio: 'btp' } },
    { id: 'build', type: 'container', position: { x: 665, y: 95 }, style: { width: 410, height: 330, zIndex: 2 }, data: { titulo: 'SAP Build', icone: 'wrench', dominio: 'btp', cardId: 'build' } },
    { id: 'bpa', type: 'item', position: { x: 760, y: 125 }, style: { width: 220, height: 40, zIndex: 3 }, data: { label: 'SAP Build Process Automation', nota: 'Decisions', cardId: 'build', dominio: 'btp' } },
    { id: 'framework', type: 'container', position: { x: 680, y: 185 }, style: { width: 380, height: 120, zIndex: 3 }, data: { titulo: 'Events-To-Business Actions Framework', dominio: 'ai', focus: true, subtitulo: 'Node.js / CAP application — referência, não produto' } },
    { id: 'modeller', type: 'item', position: { x: 695, y: 235 }, style: { width: 110, height: 34, zIndex: 4 }, data: { label: 'Modeller App', dominio: 'ai' } },
    { id: 'processor', type: 'item', position: { x: 815, y: 235 }, style: { width: 110, height: 34, zIndex: 4 }, data: { label: 'Processor Srv', dominio: 'ai' } },
    { id: 'monitoring', type: 'item', position: { x: 935, y: 235 }, style: { width: 110, height: 34, zIndex: 4 }, data: { label: 'Monitoring App', dominio: 'ai' } },
    { id: 'hana', type: 'item', position: { x: 695, y: 340 }, style: { width: 110, height: 60, zIndex: 3 }, data: { label: 'SAP HANA Cloud', cardId: 'hana-cloud', dominio: 'dados' } },
    { id: 'auth', type: 'item', position: { x: 815, y: 340 }, style: { width: 110, height: 60, zIndex: 3 }, data: { label: 'Authorization & Trust Mgmt', dominio: 'identidade' } },
    { id: 'logging', type: 'item', position: { x: 935, y: 340 }, style: { width: 110, height: 60, zIndex: 3 }, data: { label: 'Application Logging', dominio: 'btp' } },
    { id: 'ias', type: 'container', position: { x: 490, y: 480 }, style: { width: 600, height: 120, zIndex: 1 }, data: { titulo: 'SAP Cloud Identity Services', icone: 'shield', dominio: 'identidade', cardId: 'ias' } },
    { id: 'ias-dir', type: 'item', position: { x: 620, y: 520 }, style: { width: 130, height: 60, zIndex: 2 }, data: { label: 'Identity Directory', dominio: 'identidade' } },
    { id: 'ias-auth', type: 'item', position: { x: 765, y: 520 }, style: { width: 130, height: 60, zIndex: 2 }, data: { label: 'Identity Authentication', dominio: 'identidade' } },
    { id: 'ias-prov', type: 'item', position: { x: 910, y: 520 }, style: { width: 130, height: 60, zIndex: 2 }, data: { label: 'Identity Provisioning', dominio: 'identidade' } },
    { id: 'conn', type: 'item', position: { x: 1130, y: 150 }, style: { width: 100, height: 60, zIndex: 1 }, data: { label: 'Connectivity service', cardId: 'cloud-connector', dominio: 'btp' } },
    { id: 'dest', type: 'item', position: { x: 1130, y: 260 }, style: { width: 100, height: 60, zIndex: 1 }, data: { label: 'Destination service', dominio: 'btp' } },
    { id: 'network', type: 'network', position: { x: 1250, y: 20 }, style: { width: 30, height: 600, zIndex: 1 }, data: { label: 'NETWORK' } },
    { id: 'ext-onprem', type: 'container', position: { x: 1300, y: 110 }, style: { width: 190, height: 95, zIndex: 0 }, data: { titulo: 'SAP On-Premise Solutions', dashed: true, dominio: 'onprem', subtitulo: 'Cloud Connector', cardId: 's4-any' } },
    { id: 'ext-3rd', type: 'container', position: { x: 1300, y: 230 }, style: { width: 190, height: 70, zIndex: 0 }, data: { titulo: '3rd Party APIs & Applications', dashed: true, dominio: 'nonsap' } },
    { id: 'ext-cloud', type: 'container', position: { x: 1300, y: 330 }, style: { width: 190, height: 90, zIndex: 0 }, data: { titulo: 'SAP Cloud Solutions', dashed: true, dominio: 'sap', subtitulo: 'S/4HANA Cloud', cardId: 's4hana' } },
    { id: 'idp-3rd', type: 'actor', position: { x: 760, y: 640 }, data: { label: '3rd party identity provider', icone: 'user' } },
  ],
  edges: [
    { id: 'e1', source: 'sources', target: 'producers', type: 'sapEdge', label: '②', data: { tipo: 'nativa', animado: true, frase: 'Sensores, MES e sistemas logísticos publicam eventos nos produtores.' } },
    { id: 'e2', source: 'producers', target: 'aem', type: 'sapEdge', label: '③ publish', data: { tipo: 'nativa', animado: true, frase: 'Os produtores publicam na Advanced Event Mesh (ou Event Mesh da Integration Suite).' } },
    { id: 'e3', source: 'aem', target: 'framework', type: 'sapEdge', label: '④ subscribe', data: { tipo: 'nativa', animado: true, frase: 'O Processor subscreve a fila; o evento chega ao framework CAP.' } },
    { id: 'e4', source: 'bpa', target: 'framework', type: 'sapEdge', label: 'Decisions', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'extensao', animado: true, frase: 'Build Process Automation Decisions derivam a acção de negócio a partir das características do evento.' } },
    { id: 'e5', source: 'framework', target: 'dest', type: 'sapEdge', label: '⑤', data: { tipo: 'nativa', animado: true, frase: 'A acção sai por Destination + Connectivity.' } },
    { id: 'e6', source: 'conn', target: 'ext-onprem', type: 'sapEdge', label: 'HTTPS', data: { tipo: 'rede', animado: true, frase: 'Cloud Connector até ao S/4 / ECC on-prem — cria a ordem, notificação de manutenção, etc.' } },
    { id: 'e7', source: 'dest', target: 'ext-cloud', type: 'sapEdge', label: 'HTTPS', data: { tipo: 'nativa', animado: true, frase: 'Ou directamente no S/4HANA Cloud.' } },
    { id: 'e8', source: 'actor-clients', target: 'workzone', type: 'sapEdge', label: '① SAML2/OIDC', data: { tipo: 'auth', animado: false, frase: 'O administrador entra pelo Work Zone e configura regras e acções no Modeller.' } },
    { id: 'e9', source: 'ias', target: 'subaccount', type: 'sapEdge', label: 'OIDC', sourceHandle: 't', targetHandle: 'b', data: { tipo: 'auth', animado: false, frase: 'Trust entre o subaccount e o IAS.' } },
    { id: 'e10', source: 'idp-3rd', target: 'ias', type: 'sapEdge', label: 'SAML2/OIDC', sourceHandle: undefined, targetHandle: 'b', data: { tipo: 'auth', animado: false, frase: 'IdP corporativo federado ao IAS.' } },
    { id: 'e11', source: 'framework', target: 'auth', type: 'sapEdge', label: 'Trust', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'auth', animado: false, frase: 'Trust entre a app e o Authorization & Trust Management (XSUAA).' } },
  ],
}
