// Cenário Cloud Pública — GROW / S/4HANA Cloud Public Edition (secção 13).
export default {
  id: 'grow',
  titulo: { pt: 'Cloud Pública — GROW', en: 'Public Cloud — GROW', fr: 'Cloud public — GROW', de: 'Public Cloud — GROW', es: 'Nube Pública — GROW' },
  hero: { pt: 'Browser → IAS → Web Dispatcher → S/4HANA Cloud Public Edition + HANA gerido. Integration Suite para sistemas remotos, Datasphere/BDC → SAC, Cloud ALM a observar.', en: 'Browser → IAS → Web Dispatcher → S/4HANA Cloud Public Edition + managed HANA. Integration Suite for remote systems, Datasphere/BDC → SAC, Cloud ALM watching.' },
  fonte: 'Mapa do ecossistema — cenário L1 (baseado no diagrama simples S/4HANA Cloud Public Edition)',
  dominio: 'appdev',
  presetDefault: 'cloud',
  cenarios: [{ id: 'completo', nome: { pt: 'Fluxo completo', en: 'Full flow' } }],
  computarEstiloNo: () => ({}),
  nodes: [
    { id: 'actor-user', type: 'actor', position: { x: 10, y: 180 }, data: { label: 'Business user (browser)', icone: 'user' } },
    { id: 'actor-remote', type: 'actor', position: { x: 10, y: 420 }, data: { label: 'Sistema remoto', icone: 'server' } },
    { id: 'sap-cloud', type: 'container', position: { x: 170, y: 20 }, style: { width: 760, height: 600, zIndex: 0 }, data: { titulo: 'SAP Cloud (operado pela SAP)', numero: '①', icone: 'cloud', dominio: 'sap' } },
    { id: 'ias', type: 'item', position: { x: 200, y: 120 }, style: { width: 170, height: 55, zIndex: 2 }, data: { label: 'SAP Cloud Identity Services', nota: 'IdP · IAS / IPS', cardId: 'ias', dominio: 'identidade' } },
    { id: 'wd', type: 'item', position: { x: 200, y: 200 }, style: { width: 170, height: 50, zIndex: 2 }, data: { label: 'SAP Web Dispatcher', nota: 'reverse proxy', dominio: 'sap' } },
    { id: 's4', type: 'container', position: { x: 420, y: 90 }, style: { width: 270, height: 190, zIndex: 1 }, data: { titulo: 'S/4HANA Cloud Public Edition', numero: '②', dominio: 'sap', cardId: 's4hana' } },
    { id: 's4-item', type: 'item', position: { x: 435, y: 130 }, style: { width: 240, height: 50, zIndex: 2 }, data: { label: 'S/4HANA Server', nota: 'processos standard · Fiori', cardId: 's4hana' } },
    { id: 'hana', type: 'item', position: { x: 435, y: 195 }, style: { width: 240, height: 45, zIndex: 2 }, data: { label: 'SAP HANA (gerido)', cardId: 'hana-cloud', dominio: 'dados' } },
    { id: 'btp', type: 'container', position: { x: 730, y: 90 }, style: { width: 180, height: 190, zIndex: 1 }, data: { titulo: 'BTP', numero: '③', dominio: 'btp', cardId: 'btp' } },
    { id: 'isuite', type: 'item', position: { x: 745, y: 130 }, style: { width: 150, height: 50, zIndex: 2 }, data: { label: 'Integration Suite', cardId: 'integration-suite', dominio: 'btp' } },
    { id: 'build', type: 'item', position: { x: 745, y: 195 }, style: { width: 150, height: 45, zIndex: 2 }, data: { label: 'Build · Work Zone', cardId: 'build', dominio: 'btp' } },
    { id: 'dados', type: 'container', position: { x: 200, y: 330 }, style: { width: 490, height: 120, zIndex: 1 }, data: { titulo: 'Dados & Analytics', numero: '④', dominio: 'dados' } },
    { id: 'datasphere', type: 'item', position: { x: 215, y: 370 }, style: { width: 220, height: 50, zIndex: 2 }, data: { label: 'Datasphere / Business Data Cloud', cardId: 'bdc', dominio: 'dados' } },
    { id: 'sac', type: 'item', position: { x: 455, y: 370 }, style: { width: 220, height: 50, zIndex: 2 }, data: { label: 'SAP Analytics Cloud', cardId: 'sac', dominio: 'dados' } },
    { id: 'alm', type: 'container', position: { x: 200, y: 490 }, style: { width: 710, height: 110, zIndex: 1 }, data: { titulo: 'Cloud ALM · Signavio · SAP for Me', numero: '⑤', icone: 'shield', dominio: 'alm', subtitulo: 'Activate · operações · fit-to-standard · tenant pedido em SAP for Me', cardId: 'cloud-alm' } },
  ],
  edges: [
    { id: 'e1', source: 'actor-user', target: 'ias', type: 'sapEdge', label: 'Authentication', data: { tipo: 'auth', animado: true, frase: 'O IdP corporativo (Entra ID, Okta) federa-se ao IAS.' } },
    { id: 'e2', source: 'ias', target: 'wd', type: 'sapEdge', label: 'SSO', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'auth', animado: true, frase: 'Token SAML/OIDC segue para o Web Dispatcher.' } },
    { id: 'e3', source: 'wd', target: 's4', type: 'sapEdge', label: 'System access', data: { tipo: 'nativa', animado: true, frase: 'HTTPS ao S/4HANA Cloud — Fiori standard.' } },
    { id: 'e4', source: 'actor-remote', target: 'isuite', type: 'sapEdge', label: 'HTTPS / API', data: { tipo: 'nativa', animado: true, frase: 'Sistemas remotos entram pela Integration Suite, não directamente no S/4.' } },
    { id: 'e5', source: 'isuite', target: 's4', type: 'sapEdge', label: 'system-to-system', data: { tipo: 'extensao', animado: true, frase: 'iFlows / APIs released — integração técnica upgrade-safe.' } },
    { id: 'e6', source: 's4', target: 'dados', type: 'sapEdge', label: 'live analytics', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'nativa', animado: true, frase: 'Dados do S/4 fluem para Datasphere/BDC e daí para o SAC.' } },
    { id: 'e7', source: 'alm', target: 's4', type: 'sapEdge', label: 'observa', sourceHandle: 't', targetHandle: 'b', data: { tipo: 'governa', animado: false, frase: 'Cloud ALM observa e governa; Signavio decide o processo.' } },
  ],
}
