// SCH-JOULE-STACK — imagem 1: AI-native North Star simplificado (secção 17).
// Fonte: architecture.learning.sap.com/docs/ai-native-north-star-architecture
// (paper actualizado 13 Mai 2026, PDF Q2 2026). Reconstruído com nós React
// Flow + labels oficiais dos blocos; não é o PNG original.
export default {
  id: 'joule-stack',
  titulo: { pt: 'North Star AI — stack Joule', en: 'North Star AI — Joule stack', fr: 'North Star IA — pile Joule', de: 'North Star KI — Joule-Stack', es: 'North Star IA — stack Joule' },
  hero: { pt: 'Joule como orquestrador central sobre um Agent Layer, um AI Layer e um Data Layer — tudo dentro do BTP, com gateway governado para agentes e IA não-SAP.', en: 'Joule as central orchestrator over an Agent Layer, an AI Layer and a Data Layer — all inside BTP, with a governed gateway to non-SAP agents and AI.' },
  fonte: 'SAP Architecture Center — AI-native North Star architecture (Mai 2026)',
  dominio: 'ai',
  northStar: true,
  cenarios: [{ id: 'completo', nome: { pt: 'Stack completo', en: 'Full stack' } }],
  computarEstiloNo: () => ({}),
  nodes: [
    { id: 'partner-apps', type: 'container', position: { x: 10, y: 10 }, style: { width: 150, height: 80, zIndex: 0 }, data: { titulo: 'Customer and Partner Apps', dominio: 'nonsap' } },
    { id: 'sap-apps', type: 'container', position: { x: 180, y: 10 }, style: { width: 780, height: 80, zIndex: 0 }, data: { titulo: 'SAP Applications', dominio: 'sap', cardId: 'business-suite' } },
    { id: 'joule-client', type: 'item', position: { x: 195, y: 45 }, style: { width: 750, height: 34, zIndex: 1 }, data: { label: 'Joule Client', cardId: 'joule', dominio: 'ai' } },
    { id: 'btp', type: 'container', position: { x: 10, y: 120 }, style: { width: 950, height: 420, zIndex: 0 }, data: { titulo: 'Business Technology Platform', icone: 'cloud', dominio: 'btp', cardId: 'btp' } },
    { id: 'studio', type: 'item', position: { x: 30, y: 160, }, style: { width: 120, height: 130, zIndex: 2 }, data: { label: 'Joule Studio', nota: 'Design-Time', cardId: 'joule-studio', dominio: 'ai' } },
    { id: 'joule', type: 'container', position: { x: 170, y: 155 }, style: { width: 640, height: 55, zIndex: 1 }, data: { titulo: 'Joule', dominio: 'ai', subtitulo: 'Central Orchestrator', cardId: 'joule' } },
    { id: 'agent-layer', type: 'container', position: { x: 170, y: 220 }, style: { width: 640, height: 75, zIndex: 1 }, data: { titulo: 'Agent Layer', dominio: 'ai' } },
    { id: 'ag-content', type: 'item', position: { x: 185, y: 250 }, style: { width: 140, height: 34, zIndex: 2 }, data: { label: 'Content-based Agents', dominio: 'ai' } },
    { id: 'ag-code', type: 'item', position: { x: 340, y: 250 }, style: { width: 140, height: 34, zIndex: 2 }, data: { label: 'Code-based Agents', dominio: 'ai' } },
    { id: 'ag-workflows', type: 'item', position: { x: 495, y: 250 }, style: { width: 140, height: 34, zIndex: 2 }, data: { label: 'Agentic Workflows', cardId: 'build', dominio: 'ai' } },
    { id: 'ag-tools', type: 'item', position: { x: 650, y: 250 }, style: { width: 145, height: 34, zIndex: 2 }, data: { label: 'Agent Tools', dominio: 'ai' } },
    { id: 'gateway', type: 'item', position: { x: 830, y: 155 }, style: { width: 110, height: 140, zIndex: 2 }, data: { label: 'Agent & Tool Gateway', nota: 'governado', cardId: 'ai-agent-hub', dominio: 'btp' } },
    { id: 'ai-layer', type: 'container', position: { x: 30, y: 310 }, style: { width: 910, height: 95, zIndex: 1 }, data: { titulo: 'AI Layer', dominio: 'ai', cardId: 'ai-foundation' } },
    { id: 'ai-core', type: 'item', position: { x: 45, y: 345 }, style: { width: 160, height: 45, zIndex: 2 }, data: { label: 'AI Core & GenAI Hub', cardId: 'ai-foundation', dominio: 'ai' } },
    { id: 'pal', type: 'item', position: { x: 220, y: 345 }, style: { width: 160, height: 45, zIndex: 2 }, data: { label: 'HANA PAL & APL', cardId: 'hana-cloud', dominio: 'dados' } },
    { id: 'kg', type: 'item', position: { x: 395, y: 345 }, style: { width: 160, height: 45, zIndex: 2 }, data: { label: 'Knowledge Graph', cardId: 'knowledge-graph', dominio: 'dados' } },
    { id: 'vector', type: 'item', position: { x: 570, y: 345 }, style: { width: 160, height: 45, zIndex: 2 }, data: { label: 'HANA Vector Engine', cardId: 'hana-cloud', dominio: 'dados' } },
    { id: 'fm', type: 'item', position: { x: 745, y: 345 }, style: { width: 180, height: 45, zIndex: 2 }, data: { label: 'Foundational Models', nota: 'e.g. RPT-1', dominio: 'ai' } },
    { id: 'data-layer', type: 'container', position: { x: 30, y: 420 }, style: { width: 910, height: 105, zIndex: 1 }, data: { titulo: 'Data Layer', dominio: 'dados' } },
    { id: 'bdc', type: 'item', position: { x: 45, y: 452 }, style: { width: 880, height: 30, zIndex: 2 }, data: { label: 'Business Data Cloud', cardId: 'bdc', dominio: 'dados' } },
    { id: 'hana-cloud', type: 'item', position: { x: 45, y: 488 }, style: { width: 880, height: 30, zIndex: 2 }, data: { label: 'HANA Cloud (incl. Vector and Knowledge Graph Engine)', cardId: 'hana-cloud', dominio: 'dados' } },
    { id: 'nonsap', type: 'container', position: { x: 990, y: 120 }, style: { width: 190, height: 300, zIndex: 0 }, data: { titulo: 'Non-SAP', dashed: true, dominio: 'nonsap' } },
    { id: 'agent-platforms', type: 'container', position: { x: 1005, y: 160 }, style: { width: 160, height: 115, zIndex: 1 }, data: { titulo: 'Agent Platforms', dominio: 'nonsap' } },
    { id: 'ext-agents', type: 'item', position: { x: 1015, y: 195 }, style: { width: 140, height: 34, zIndex: 2 }, data: { label: 'Agents', nota: '3rd-party, custom', dominio: 'nonsap' } },
    { id: 'ext-tools', type: 'item', position: { x: 1015, y: 235 }, style: { width: 140, height: 34, zIndex: 2 }, data: { label: 'Agent Tools', nota: '3rd-party, custom', dominio: 'nonsap' } },
    { id: 'ai-services', type: 'container', position: { x: 1005, y: 290 }, style: { width: 160, height: 115, zIndex: 1 }, data: { titulo: 'AI Services', dominio: 'nonsap' } },
    { id: 'llms', type: 'item', position: { x: 1015, y: 325 }, style: { width: 140, height: 60, zIndex: 2 }, data: { label: 'LLMs, Grounding', dominio: 'nonsap' } },
  ],
  edges: [
    { id: 'e1', source: 'joule-client', target: 'joule', type: 'sapEdge', label: 'R', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'nativa', animado: true, frase: 'Request: o utilizador fala com o Joule Client dentro da app SAP; o orquestrador central decide.' } },
    { id: 'e2', source: 'partner-apps', target: 'studio', type: 'sapEdge', label: 'R', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'nativa', animado: true, frase: 'Apps de cliente/parceiro entram pelo mesmo stack via Joule Studio / API.' } },
    { id: 'e3', source: 'joule', target: 'agent-layer', type: 'sapEdge', label: 'delega', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'nativa', animado: true, frase: 'O orquestrador delega em agentes de conteúdo, de código, workflows agênticos e tools.' } },
    { id: 'e4', source: 'agent-layer', target: 'ai-layer', type: 'sapEdge', label: 'usa', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'nativa', animado: true, frase: 'Os agentes correm sobre AI Core / GenAI Hub, PAL/APL, Knowledge Graph, Vector Engine e modelos.' } },
    { id: 'e5', source: 'ai-layer', target: 'data-layer', type: 'sapEdge', label: 'grounding', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'nativa', animado: true, frase: 'Business Data Cloud + HANA Cloud são o system of context: sem eles a IA trabalha sem contexto de processo.' } },
    { id: 'e6', source: 'gateway', target: 'agent-platforms', type: 'sapEdge', label: 'A2A / MCP', data: { tipo: 'extensao', animado: true, frase: 'Gateway governado para agentes e tools não-SAP (protocolos abertos).' } },
    { id: 'e7', source: 'gateway', target: 'ai-services', type: 'sapEdge', label: 'R', data: { tipo: 'extensao', animado: false, frase: 'Acesso a LLMs e grounding externos, sempre pela gateway.' } },
  ],
}
