// Cenário Híbrido — RISE / S/4HANA Cloud Private Edition em Azure hub-spoke
// (secção 12 SCH-AZURE-RISE + secção 13). Estrutura reproduzida com formas
// geométricas, sem ícones Microsoft. Numeração ①–⑪ como o esquema original.
export default {
  id: 'rise-azure',
  titulo: { pt: 'Híbrido — RISE em Azure (hub-spoke)', en: 'Hybrid — RISE on Azure (hub-spoke)', fr: 'Hybride — RISE sur Azure (hub-spoke)', de: 'Hybrid — RISE auf Azure (Hub-Spoke)', es: 'Híbrido — RISE en Azure (hub-spoke)' },
  hero: { pt: 'On-prem → ExpressRoute → Hub Azure → Spoke prod (Web Dispatcher, ASCS, App, HANA). Perimeter com SAProuter + Cloud Connector → BTP por Private Link. DR em baixo, L6 em cima.', en: 'On-prem → ExpressRoute → Azure Hub → Prod spoke (Web Dispatcher, ASCS, App, HANA). Perimeter with SAProuter + Cloud Connector → BTP via Private Link. DR below, L6 on top.' },
  fonte: 'Azure Architecture Center — SAP on Azure landing zone (estrutura), reconstruído',
  dominio: 'opsec',
  presetDefault: 'rise',
  hyperscalerDefault: 'azure',
  cenarios: [{ id: 'completo', nome: { pt: 'Fluxo completo', en: 'Full flow' } }],
  computarEstiloNo: () => ({}),
  nodes: [
    { id: 'alm', type: 'container', position: { x: 170, y: 10 }, style: { width: 1000, height: 70, zIndex: 0 }, data: { titulo: 'L6 — Cloud ALM · Signavio · LeanIX · Deploy with Confidence', icone: 'shield', dominio: 'alm', subtitulo: 'governa o clean core e a implantação do to-be', cardId: 'cloud-alm' } },
    { id: 'onprem', type: 'container', position: { x: 10, y: 120 }, style: { width: 140, height: 120, zIndex: 0 }, data: { titulo: 'On-premises', numero: '①', icone: 'server', dominio: 'onprem', subtitulo: 'gateway do cliente', cardId: 'dc-onprem' } },
    { id: 'hub-sub', type: 'container', position: { x: 170, y: 100 }, style: { width: 300, height: 260, zIndex: 0 }, data: { titulo: 'Azure subscription: Regional hubs', numero: '②', icone: 'cloud', dominio: 'azure', cardId: 'azure' } },
    { id: 'hub-vnet', type: 'container', position: { x: 185, y: 140 }, style: { width: 270, height: 205, zIndex: 1 }, data: { titulo: 'Hub VNet (região primária)', numero: '③', dominio: 'azure' } },
    { id: 'gw', type: 'item', position: { x: 200, y: 175 }, style: { width: 240, height: 40, zIndex: 2 }, data: { label: 'Gateway subnet', nota: 'ExpressRoute · zone-redundant', dominio: 'azure' } },
    { id: 'fw', type: 'item', position: { x: 200, y: 222 }, style: { width: 240, height: 36, zIndex: 2 }, data: { label: 'Azure Firewall subnet', dominio: 'azure' } },
    { id: 'shared', type: 'item', position: { x: 200, y: 265 }, style: { width: 240, height: 36, zIndex: 2 }, data: { label: 'Shared services (AD / DNS) · App Gateway', dominio: 'azure' } },
    { id: 'prod-sub', type: 'container', position: { x: 500, y: 100 }, style: { width: 420, height: 260, zIndex: 0 }, data: { titulo: 'Subscription SAP production (gerida pela SAP)', numero: '⑦', icone: 'cloud', dominio: 'azure', cardId: 's4hana' } },
    { id: 'spoke-prod', type: 'container', position: { x: 515, y: 140 }, style: { width: 390, height: 205, zIndex: 1 }, data: { titulo: 'Spoke production VNet', numero: '⑧', dominio: 'sap' } },
    { id: 'perimeter', type: 'item', position: { x: 530, y: 175 }, style: { width: 360, height: 40, zIndex: 2 }, data: { label: 'Perimeter subnet', nota: 'SAProuter + Cloud Connector', cardId: 'cloud-connector' } },
    { id: 'app', type: 'item', position: { x: 530, y: 222 }, style: { width: 360, height: 40, zIndex: 2 }, data: { label: 'Application subnet', nota: 'Web Dispatcher pool · ASCS · App VMs', cardId: 's4hana' } },
    { id: 'db', type: 'item', position: { x: 530, y: 269 }, style: { width: 360, height: 40, zIndex: 2 }, data: { label: 'Database subnet', nota: 'HANA · Azure Files / NetApp', dominio: 'dados', cardId: 's4hana' } },
    { id: 'btp', type: 'container', position: { x: 950, y: 100 }, style: { width: 220, height: 260, zIndex: 0 }, data: { titulo: 'SAP BTP', numero: '⑪', icone: 'wrench', dominio: 'btp', cardId: 'btp' } },
    { id: 'btp-dev', type: 'item', position: { x: 965, y: 145 }, style: { width: 190, height: 36, zIndex: 1 }, data: { label: 'Subaccount DEV', dominio: 'btp' } },
    { id: 'btp-qas', type: 'item', position: { x: 965, y: 189 }, style: { width: 190, height: 36, zIndex: 1 }, data: { label: 'Subaccount QAS', dominio: 'btp' } },
    { id: 'btp-prd', type: 'item', position: { x: 965, y: 233 }, style: { width: 190, height: 36, zIndex: 1 }, data: { label: 'Subaccount PRD', dominio: 'btp' } },
    { id: 'btp-svc', type: 'item', position: { x: 965, y: 285 }, style: { width: 190, height: 55, zIndex: 1 }, data: { label: 'Build · Integration Suite · IAS', nota: 'ao lado, não em cima do S/4', cardId: 'integration-suite', dominio: 'btp' } },
    { id: 'nonprod-sub', type: 'container', position: { x: 170, y: 390 }, style: { width: 750, height: 110, zIndex: 0 }, data: { titulo: 'Subscription SAP non-production', numero: '⑤', dashed: true, dominio: 'azure' } },
    { id: 'spoke-sbx', type: 'item', position: { x: 185, y: 430 }, style: { width: 230, height: 50, zIndex: 1 }, data: { label: 'Spoke Sandbox', nota: 'App + DB subnets', dominio: 'sap' } },
    { id: 'spoke-dev', type: 'item', position: { x: 430, y: 430 }, style: { width: 230, height: 50, zIndex: 1 }, data: { label: 'Spoke Development', nota: 'App + DB subnets', dominio: 'sap' } },
    { id: 'spoke-qa', type: 'item', position: { x: 675, y: 430 }, style: { width: 230, height: 50, zIndex: 1 }, data: { label: 'Spoke Pre-prod / QA', nota: 'App + DB subnets', dominio: 'sap' } },
    { id: 'dr-line', type: 'network', position: { x: 170, y: 515 }, style: { width: 1000, height: 20, zIndex: 0 }, data: { label: 'Primary region  ·  ·  ·  Disaster recovery region' } },
    { id: 'dr-hub', type: 'container', position: { x: 170, y: 550 }, style: { width: 300, height: 90, zIndex: 0 }, data: { titulo: 'Hub VNet DR', numero: '④', dominio: 'dr', subtitulo: 'mesmo padrão na região DR' } },
    { id: 'dr-spoke', type: 'container', position: { x: 500, y: 550 }, style: { width: 420, height: 90, zIndex: 0 }, data: { titulo: 'Spoke production DR', numero: '⑨', dominio: 'dr', subtitulo: 'espelho · Azure Site Recovery' } },
    { id: 'shared-azure', type: 'container', position: { x: 950, y: 550 }, style: { width: 220, height: 90, zIndex: 0 }, data: { titulo: 'Serviços Azure partilhados', numero: '⑩', dashed: true, dominio: 'azure', subtitulo: 'Cloud Witness · Data Factory · Recovery vault' } },
  ],
  edges: [
    { id: 'e1', source: 'onprem', target: 'hub-sub', type: 'sapEdge', label: 'ExpressRoute', data: { tipo: 'rede', animado: true, frase: 'Circuito privado on-prem ↔ hub; VPN como backup para a região DR.' } },
    { id: 'e2', source: 'hub-sub', target: 'prod-sub', type: 'sapEdge', label: 'VNet peering hub ↔ spoke', data: { tipo: 'rede', animado: true, frase: 'Todo o tráfego passa pelo hub (firewall, DNS, inspecção).' } },
    { id: 'e3', source: 'spoke-prod', target: 'btp', type: 'sapEdge', label: 'Private Link for SAP BTP', data: { tipo: 'extensao', animado: true, frase: 'Ligação privada do spoke ao BTP sem sair à Internet (card private-link).' } },
    { id: 'e4', source: 'perimeter', target: 'btp-svc', type: 'sapEdge', label: 'Cloud Connector (túnel outbound)', data: { tipo: 'rede', animado: true, frase: 'Sem inbound no firewall; RFC/OData expostos ao BTP de forma controlada.' } },
    { id: 'e5', source: 'prod-sub', target: 'dr-spoke', type: 'sapEdge', label: 'HANA System Replication', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'dr', animado: true, frase: 'HSR async para a região DR; Azure Site Recovery para as VMs de app.' } },
    { id: 'e6', source: 'hub-sub', target: 'nonprod-sub', type: 'sapEdge', label: 'peering', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'rede', animado: false, frase: 'Spokes não-produtivos partilham o mesmo hub.' } },
    { id: 'e7', source: 'alm', target: 'prod-sub', type: 'sapEdge', label: 'clean core / side-by-side', sourceHandle: 'b', targetHandle: 't', data: { tipo: 'governa', animado: false, frase: 'Cloud ALM mede o clean core; custom code vai para o BTP, não para o S/4.' } },
  ],
}
