// Ícones genéricos/geométricos por 'tipo' de serviço — nunca logótipos SAP ou
// de vendors. A cor da camada + o nome do card distinguem o serviço; o ícone
// só dá a categoria de relance. Mapeamento explícito para as categorias mais
// frequentes/relevantes; para qualquer 'tipo' fora da lista (sobretudo os
// satélites do Apêndice A), obterIcone() cai num fallback por palavra-chave
// e, por fim, num ícone genérico — nunca falha nem fica sem ícone.
import {
  BrainCircuit, Sparkles, ClipboardCheck, ClipboardList, ShieldAlert, BarChart3, PieChart,
  Smartphone, Wrench, Car, FileSpreadsheet, BarChart2, Landmark, Receipt, FileCheck2, Globe2,
  Link2, FileStack, UserCircle, HardDrive, Database, Fingerprint, Brain, Share2, Archive,
  Hammer, MousePointerClick, Radio, RadioTower, Cloud, Building2, Building, History, Server,
  Network, Map, GraduationCap, Wallet, UserCog, ShieldCheck, Vault, KeyRound, Factory,
  Waypoints, ArrowRightLeft, Compass, Activity, Boxes, Store, LayoutGrid,
  CalendarClock, Workflow, Handshake, Percent, Shirt, Cpu, GitMerge, Heart, Users,
  CalendarRange, ShoppingCart, Plane, UserPlus, Leaf, TestTube2, Truck, MonitorSmartphone,
  LayoutDashboard, MonitorX, Zap, PackageCheck, MapPin, Coins, Box,
  Siren, Puzzle, FileText, Repeat, Fuel, Stethoscope, Umbrella,
} from 'lucide-react'

export const ICONE_POR_TIPO = {
  'AI': BrainCircuit,
  'AI / Assistente': Sparkles,
  'AI Finance': Coins,
  'ALM SaaS': ClipboardCheck,
  'ALM on-prem': ClipboardList,
  'Ambiente e segurança': ShieldAlert,
  'Analytics + Planning': BarChart3,
  'Analytics Spend': PieChart,
  'App móvel': Smartphone,
  'App RH': Users,
  'Asset SaaS': Wrench,
  'Automotive': Car,
  'BI Excel': FileSpreadsheet,
  'BI clássico': BarChart2,
  'Banca': Landmark,
  'Billing de subscrição': Receipt,
  'Colaboração fornecedor': Handshake,
  'Compliance fiscal': FileCheck2,
  'Comércio externo': Globe2,
  'Connectivity': Link2,
  'Consolidação': FileStack,
  'Customer portal': UserCircle,
  'DB': HardDrive,
  'DBPaaS': Database,
  'Dados mestres': Fingerprint,
  'Data + AI': Brain,
  'Data Fabric': Share2,
  'Data Warehouse': Archive,
  'Data pipeline': Waypoints,
  'Dev + Low-code': Hammer,
  'Digital Manufacturing': Factory,
  'Digital adoption': MousePointerClick,
  'EDA': Radio,
  'EDA enterprise': RadioTower,
  'ERP Cloud': Cloud,
  'ERP PME': Building2,
  'ERP PME Cloud': Building,
  'ERP ancestral': History,
  'ERP legado': History,
  'ERP on-prem': Server,
  'ETL': Repeat,
  'EiPaaS': Network,
  'Enterprise Architecture': Map,
  'Finanças centrais': Landmark,
  'Formação': GraduationCap,
  'Gateway Spend': Wallet,
  'Governação PLM': ShieldCheck,
  'HR on-prem': UserCog,
  'IAM / SoD cloud': ShieldCheck,
  'IaaS': Cloud,
  'IaaS soberana': Vault,
  'IaaS soberano': Vault,
  'IdP / IAM': KeyRound,
  'Imobiliário': Building,
  'Inbox unificada': LayoutGrid,
  'Integração': Waypoints,
  'MES Cloud': Factory,
  'MES clássico': Factory,
  'MDG add-on': Fingerprint,
  'Método': Compass,
  'On-prem': Server,
  'Ops de landscape': Boxes,
  'PLM Cloud': Puzzle,
  'PLM clássico': Puzzle,
  'PaaS': LayoutGrid,
  'PaaS on-prem': Server,
  'Planning legado': CalendarRange,
  'Portefólio soberania': Vault,
  'Process Intelligence': Activity,
  'Projectos': ClipboardList,
  'Rastreio': MapPin,
  'Receita': Coins,
  'Rede': Network,
  'Relato': FileText,
  'Rentabilidade': Percent,
  'Reporting legado': FileSpreadsheet,
  'Retail moda': Shirt,
  'Risco e controlo': ShieldAlert,
  'Runtime': Cpu,
  'Runtime híbrido': GitMerge,
  'SaaS CX': Heart,
  'SaaS HCM': Users,
  'SaaS Planning': CalendarClock,
  'SaaS Procurement': ShoppingCart,
  'SaaS T&E': Plane,
  'SaaS VMS': UserPlus,
  'Segurança': Siren,
  'Sustentabilidade': Leaf,
  'Testes': TestTube2,
  'Tesouraria': Landmark,
  'Transportes': Truck,
  'UX': MonitorSmartphone,
  'UX / Launchpad': LayoutDashboard,
  'UX clássico': MonitorX,
  'UX legado': MonitorX,
  'Vertical': Compass,
  'Warehouse': PackageCheck,
  'Working capital': Coins,
}

// Fallback por palavra-chave (aplicado a qualquer 'tipo' não mapeado acima,
// sobretudo os satélites do Apêndice A). Testado por ordem — primeira que
// bater define o ícone.
const REGRAS_FALLBACK = [
  [/legado|clássico|ancestral/i, History],
  [/IA\b|inteligente|AI\b/i, BrainCircuit],
  [/soberan/i, Vault],
  [/GRC|risco|compliance|regula/i, ShieldAlert],
  [/testes?|teste/i, TestTube2],
  [/PLM|produto/i, Puzzle],
  [/warehouse|armazém|yard/i, PackageCheck],
  [/transporte|TM\b|logístic/i, Truck],
  [/RH|HR|colaborador|workforce|recruit/i, Users],
  [/finança|tesouraria|receita|fatur|invoice/i, Coins],
  [/sustentabilidade|ESG|carbono|verde/i, Leaf],
  [/identidade|IAM|SSO|IdP/i, KeyRound],
  [/rede|network|conectiv/i, Network],
  [/dados|data|metadados/i, Database],
  [/analytics|KPI|planning|forecast/i, BarChart3],
  [/utilities|energia/i, Zap],
  [/retalho|retail|loja|POS/i, Store],
  [/seguros|insurance/i, Umbrella,],
  [/oil|gas|tank/i, Fuel],
  [/saúde|healthcare/i, Stethoscope],
  [/processo|workflow|automat/i, Workflow],
  [/formação|enablement|suporte/i, GraduationCap],
  [/migração|replicação/i, ArrowRightLeft],
]

export function obterIcone(tipo) {
  if (ICONE_POR_TIPO[tipo]) return ICONE_POR_TIPO[tipo]
  for (const [regra, Icone] of REGRAS_FALLBACK) {
    if (regra.test(tipo)) return Icone
  }
  return Box
}
