// Mapeia a chave "icone" de cada serviço (data.js) a um ícone geométrico
// genérico do lucide-react. Propositadamente NUNCA logótipos reais de marcas
// (SAP, AWS, Azure, GCP) — ver nota de marca no briefing.
import {
  Cloud,
  Building2,
  HardDrive,
  Database,
  Share2,
  Brain,
  LayoutGrid,
  Hammer,
  LayoutDashboard,
  KeyRound,
  Network,
  Radio,
  GitMerge,
  Link2,
  ArrowLeftRight,
  Cpu,
  Users,
  ShoppingCart,
  Workflow,
  BarChart3,
  Sparkles,
} from 'lucide-react'

export const ICONES = {
  hyperscaler: Cloud,
  datacenter: Building2,
  'hana-onprem': HardDrive,
  'hana-cloud': Database,
  datasphere: Share2,
  bdc: Brain,
  btp: LayoutGrid,
  build: Hammer,
  workzone: LayoutDashboard,
  ias: KeyRound,
  'integration-suite': Network,
  'event-mesh': Radio,
  eic: GitMerge,
  'cloud-connector': Link2,
  pipo: ArrowLeftRight,
  s4: Cpu,
  successfactors: Users,
  ariba: ShoppingCart,
  signavio: Workflow,
  sac: BarChart3,
  joule: Sparkles,
}
